# Generated by Django 5.0.4 on 2024-05-22 17:40

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('file', models.ImageField(upload_to='file/message/')),
                ('sended_at', models.DateTimeField(default=datetime.datetime(2024, 5, 22, 18, 40, 48, 343560))),
                ('readed_at', models.DateTimeField(default=datetime.datetime(2024, 5, 22, 18, 40, 48, 343560))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
