# Generated by Django 5.0.4 on 2024-05-23 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='readed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 9, 9, 7, 477810)),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='sended_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 9, 9, 7, 477810)),
        ),
    ]
