# Generated by Django 5.0.4 on 2024-05-23 11:14

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chatmodel_readed_at_alter_chatmodel_sended_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='readed_at',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='sended_at',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 12, 14, 3, 199473)),
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='file/message/')),
                ('message', models.TextField()),
                ('replying', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 23, 12, 14, 3, 199473))),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatmodel')),
            ],
        ),
    ]
