# Generated by Django 5.0.4 on 2024-05-23 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_chatmodel_file_remove_chatmodel_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='name',
            field=models.CharField(default='Asking question', max_length=150),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 12, 29, 29, 869593)),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 12, 29, 29, 869593)),
        ),
    ]
