# Generated by Django 5.0.4 on 2024-05-23 12:32

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatmodel_name_alter_chatmodel_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='chat',
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Asking question', max_length=150)),
                ('agent', models.CharField(default='CHATGPT', max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 23, 13, 32, 38, 448140))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='message/images/')),
                ('audio', models.ImageField(upload_to='message/audios/')),
                ('message', models.TextField()),
                ('from_agent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 23, 13, 32, 38, 448140))),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversation')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatModel',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
