# Generated by Django 5.0.4 on 2024-05-23 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_conversation_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='agent',
            field=models.CharField(blank=True, default='CHATGPT', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 13, 38, 21, 651748)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 13, 38, 21, 651748)),
        ),
    ]
