# Generated by Django 5.0.4 on 2024-05-23 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_conversation_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 14, 3, 58, 651657)),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.ImageField(blank=True, null=True, upload_to='message/audios/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 14, 3, 58, 653657)),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message/images/'),
        ),
    ]
